version: 0.0 
os: linux 
files:
  - source: build/reactjs
    destination: /var/www/reactjs
permissions:
  - object: /var/www/reactjs
    mod: '0755'
    pattern: '**'
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  ApplicationStart:
  - location: deployscript/application-start-hook.sh 
    timeout: 305