version: 0.2

phases:
  pre_build:
    commands:
      - echo "pre_build phase"
      - echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_USERNAME} --password-stdin
  build:
    commands:
      - docker build -t my-react:latest .
  post_build:
    commands:
      - echo "post build phases"
      - docker tag -t my-react:latest ${DOCKER_USERNAME}/my-react:latest
      - docker push ${DOCKER_USERNAME}/my-react:latest


