version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yarn install
      - NODE_OPTIONS="--max-old-space-size=4096"

  build:
    commands:
      - yarn build

artifacts:
  files:
    - appspec.yml
    - deployscript/**/*              # include your deployment scripts
    - build/reactjs/**/*             # include build output
